### ISSUE TITLE
Explain what it means for a component in "Draft" state

### ISSUE THREAD

**Issue by hamza1311** [primer/contribute#28]
There are certain components which are have the status of "Draft". See https://primer.style/react/status. This status is not explained in the [Component Lifecycle](https://primer.style/contribute/component-lifecycle).

What does it mean for a component to be "draft"? Is it usable? Does it have missing functionality?

The documentation should be updated to add this explanation

**Comment by lesliecdubs** [comment]
👋🏻 Hello @hamza1311, great question and suggestion! 

Quoting from this [Architectural Decision Record about draft components](https://github.com/primer/react/blob/main/contributor-docs/adrs/adr-006-drafts.md):

> As we work on maturity of our components, we will sometimes need to build components in a parallel track/bundle without breaking existing components. Eventually, the new components would replace the old ones in the main bundle.

This means that draft components are technically "usable," though it's probably safer to avoid consuming them directly as they are likely to change quickly. Drafts will typically be upgraded into the main bundle quickly once the rewrite/major changes are complete.

I'll check in with the team about potentially adding information about drafts to the [component lifecycle](https://primer.style/contribute/component-lifecycle) and we'll add an update here.

**Comment by lesliecdubs** [comment]
Just a quick note that this is still on our radar. You can expect an update by end of next week!

**Comment by lesliecdubs** [comment]
Hello! We have approved an [architectural decision record that will deprecate the "draft" state](https://github.com/primer/react/blob/main/contributor-docs/adrs/adr-010-drafts-are-experimental.md) in favor of using "experimental" instead, which is defined in the [component lifecycle documentation](https://primer.style/contribute/component-lifecycle#experimental).

I'm going to go ahead and close this as completed, but please comment back if there are any further questions!
